# .air.toml
[build]
  cmd = "go build -o ./tmp/main"
  bin = "./tmp/main"
  full_bin = ""
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp", "node_modules"]
  exclude_file = []
  include_dir = ["."]
  exclude_regex = ["_test.go"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
