# .air.toml
# Root của module
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main main.go"
  bin = "tmp/main"
  full_bin = true
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "yaml", "json"]
  exclude_file = ["_test.go"]

[log]
  time = true

[color]
  main = "yellow"
